apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-app.fullname" . }}
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include "spring-boot-app.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  {{- if and .Values.springBoot.management.enabled (ne .Values.springBoot.management.port .Values.service.targetPort) }}
  - port: {{ .Values.springBoot.management.port }}
    targetPort: management
    protocol: TCP
    name: management
  {{- end }}
  selector:
    {{- include "spring-boot-app.selectorLabels" . | nindent 4 }}